apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
    spec:
      containers:
        - name: items
          image: rohantiwari706/items
          env:
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: items-srv
spec:
  selector:
    app: items
  type: ClusterIP
  ports:
    - name: items
      protocol: TCP
      port: 3001
      targetPort: 3001
